version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint: "/app/run_server.sh"
    ports:
      - "80:8000"
    # env_file:
    #   - .env
    volumes:
      - .:/app/
    restart: "on-failure"
   